#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FirstSampleApp.Droid.Resource", IsApplication=true)]

namespace FirstSampleApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::xaMyo.Android.Resource.Color.myosdk__button_orange = global::FirstSampleApp.Droid.Resource.Color.myosdk__button_orange;
			global::xaMyo.Android.Resource.Color.myosdk__button_red = global::FirstSampleApp.Droid.Resource.Color.myosdk__button_red;
			global::xaMyo.Android.Resource.Color.myosdk__indicator_green = global::FirstSampleApp.Droid.Resource.Color.myosdk__indicator_green;
			global::xaMyo.Android.Resource.Color.myosdk__thalmic_blue = global::FirstSampleApp.Droid.Resource.Color.myosdk__thalmic_blue;
			global::xaMyo.Android.Resource.Dimension.myosdk__activity_horizontal_margin = global::FirstSampleApp.Droid.Resource.Dimension.myosdk__activity_horizontal_margin;
			global::xaMyo.Android.Resource.Dimension.myosdk__activity_vertical_margin = global::FirstSampleApp.Droid.Resource.Dimension.myosdk__activity_vertical_margin;
			global::xaMyo.Android.Resource.Dimension.myosdk__fragment_scan_window_height = global::FirstSampleApp.Droid.Resource.Dimension.myosdk__fragment_scan_window_height;
			global::xaMyo.Android.Resource.Dimension.myosdk__fragment_scan_window_width = global::FirstSampleApp.Droid.Resource.Dimension.myosdk__fragment_scan_window_width;
			global::xaMyo.Android.Resource.Drawable.myosdk__connected_dot = global::FirstSampleApp.Droid.Resource.Drawable.myosdk__connected_dot;
			global::xaMyo.Android.Resource.Drawable.myosdk__firmware_incompatible_dot = global::FirstSampleApp.Droid.Resource.Drawable.myosdk__firmware_incompatible_dot;
			global::xaMyo.Android.Resource.Id.myosdk__action_scan = global::FirstSampleApp.Droid.Resource.Id.myosdk__action_scan;
			global::xaMyo.Android.Resource.Id.myosdk__connection_state_dot = global::FirstSampleApp.Droid.Resource.Id.myosdk__connection_state_dot;
			global::xaMyo.Android.Resource.Id.myosdk__fragment_scan = global::FirstSampleApp.Droid.Resource.Id.myosdk__fragment_scan;
			global::xaMyo.Android.Resource.Id.myosdk__progress = global::FirstSampleApp.Droid.Resource.Id.myosdk__progress;
			global::xaMyo.Android.Resource.Id.myosdk__required_firmware_version_text = global::FirstSampleApp.Droid.Resource.Id.myosdk__required_firmware_version_text;
			global::xaMyo.Android.Resource.Id.myosdk__scan_result_view = global::FirstSampleApp.Droid.Resource.Id.myosdk__scan_result_view;
			global::xaMyo.Android.Resource.Id.text2 = global::FirstSampleApp.Droid.Resource.Id.text2;
			global::xaMyo.Android.Resource.Layout.myosdk__activity_scan = global::FirstSampleApp.Droid.Resource.Layout.myosdk__activity_scan;
			global::xaMyo.Android.Resource.Layout.myosdk__device_list_item = global::FirstSampleApp.Droid.Resource.Layout.myosdk__device_list_item;
			global::xaMyo.Android.Resource.Layout.myosdk__fragment_scan = global::FirstSampleApp.Droid.Resource.Layout.myosdk__fragment_scan;
			global::xaMyo.Android.Resource.Menu.myosdk__fragment_scan = global::FirstSampleApp.Droid.Resource.Menu.myosdk__fragment_scan;
			global::xaMyo.Android.Resource.String.app_name = global::FirstSampleApp.Droid.Resource.String.app_name;
			global::xaMyo.Android.Resource.String.hello = global::FirstSampleApp.Droid.Resource.String.hello;
			global::xaMyo.Android.Resource.String.myosdk__action_scan = global::FirstSampleApp.Droid.Resource.String.myosdk__action_scan;
			global::xaMyo.Android.Resource.String.myosdk__action_stop_scan = global::FirstSampleApp.Droid.Resource.String.myosdk__action_stop_scan;
			global::xaMyo.Android.Resource.String.myosdk__firmware_required_format = global::FirstSampleApp.Droid.Resource.String.myosdk__firmware_required_format;
			global::xaMyo.Android.Resource.String.myosdk__firmware_version_format = global::FirstSampleApp.Droid.Resource.String.myosdk__firmware_version_format;
			global::xaMyo.Android.Resource.String.myosdk__title_activity_scan = global::FirstSampleApp.Droid.Resource.String.myosdk__title_activity_scan;
			global::xaMyo.Android.Resource.String.myosdk__unknown_myo = global::FirstSampleApp.Droid.Resource.String.myosdk__unknown_myo;
			global::xaMyo.Android.Resource.Style.myosdk__PopupActivityTheme = global::FirstSampleApp.Droid.Resource.Style.myosdk__PopupActivityTheme;
			global::xaMyo.Android.Resource.Style.myosdk__ScanActivityTheme = global::FirstSampleApp.Droid.Resource.Style.myosdk__ScanActivityTheme;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int myosdk__button_orange = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int myosdk__button_red = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int myosdk__indicator_green = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int myosdk__thalmic_blue = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int myosdk__activity_horizontal_margin = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int myosdk__activity_vertical_margin = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int myosdk__fragment_scan_window_height = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int myosdk__fragment_scan_window_width = 2130837507;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int icon = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int myosdk__connected_dot = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int myosdk__firmware_incompatible_dot = 2130903042;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int myosdk__action_scan = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int myosdk__connection_state_dot = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int myosdk__fragment_scan = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int myosdk__progress = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int myosdk__required_firmware_version_text = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int myosdk__scan_result_view = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int sliding_tabs = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int text1 = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int text2 = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int toolbar = 2130968585;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050002
			public const int myosdk__activity_scan = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int myosdk__device_list_item = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int myosdk__fragment_scan = 2131034116;
			
			// aapt resource value: 0x7F050000
			public const int Tabbar = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int Toolbar = 2131034113;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F060000
			public const int myosdk__fragment_scan = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int hello = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int myosdk__action_scan = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int myosdk__action_stop_scan = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int myosdk__firmware_required_format = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int myosdk__firmware_version_format = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int myosdk__title_activity_scan = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int myosdk__unknown_myo = 2131165191;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F080000
			public const int AppCompatDialogStyle = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int MainTheme = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int MainTheme_Base = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int myosdk__PopupActivityTheme = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int myosdk__ScanActivityTheme = 2131230724;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
